branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
    - 0.10.0-legacy
cache: bundler
deploy:
  on:
    tags: true
  password:
    secure: "i2c+VGbdNJ2sFxHyF/SFq7tWAivCu2fOpITOz2j+7vM4mkgqX03H+itSl0SjnDe321LKGGAx901s5s6eKuOK6KZnt0nooa1/hTJhFyiG/qvrvefJD1pm8+0hTjBeSNw/syPFgWAlgXVqLDUkV3JYhIBLUaPV5iBemkI8H3+K1AoH7PsPUr2zX5D4xLRRu3VpvbetPpI5bUbQfkFUIPNwtMRwX9ICL631KigA0um9aa82LYq/D27GncaYPrjCX+Tzn7H/75Z7llTTfNcq9E3sbnVSZy/FdZh3qVixtoD1fjJzzJXggrhcSuQr4ADS5awyiRGj3dyhyVNamvR6t8P1nQC3e0RLmm1WPels2r76/3K4D5zOolbM1yd3A3BJAznUKNL179MznqSCZ4Fh/CRIm35BelbJdx87t8Rwl9AcJomgauX86iVOqmuDoFDWSovS8UdxqQAVYPn1pTtFjdzRhacFiFYPLFArbqqsNhekdFt0Cp0+utXastMlkfAfnxWJKp9cVxWRaNkuIFDuaBkL8qyE6AC32/VxVsOa+pDk6nXqNwR1b8z/UtHyeM+Kkgcho26WyUK2+LaQsPM6q689kCtVkfhj6Lm+gPpM90vpFOmZkfMqSViEeyY86wrUHeF7z1Bkqu+tp5BXlkkDglEI8uhSifbeTnboAlMZNBgjnQY="
  provider: puppetforge
  user: newrelic
dist: bionic
sudo: false
